package com.egeuniversity.onlineeducationsystem.Exception;

public class ErrorCodes {

    public static final String E1_CODE = "E1";
    public static final String E2_CODE = "E2";
    public static final String E3_CODE = "E3";
    public static final String E4_CODE = "E4";
    public static final String E5_CODE = "E5";
    public static final String E6_CODE = "E6";
    public static final String E7_CODE = "E7";
    public static final String E8_CODE = "E8";
    public static final String E9_CODE = "E9";
    public static final String E10_CODE = "E10";
    public static final String E11_CODE = "E11";
    public static final String E12_CODE = "E12";
    public static final String E13_CODE = "E13";
    public static final String E14_CODE = "E14";
    public static final String E15_CODE = "E15";
    public static final String E16_CODE = "E16";
    public static final String E17_CODE = "E17";
    public static final String E18_CODE = "E18";
    public static final String E19_CODE = "E19";
    public static final String E20_CODE = "E20";
    public static final String E21_CODE = "E21";
    public static final String E22_CODE = "E22";
    public static final String E23_CODE = "E23";
    public static final String E24_CODE = "E24";
    public static final String E25_CODE = "E25";
    public static final String E26_CODE = "E26";
    public static final String E27_CODE = "E27";
    public static final String E28_CODE = "E28";
    public static final String E29_CODE = "E29";

    public static final String E1_MESSAGE = "Unknown fields found: ";
    public static final String E2_MESSAGE = "Invalid parameters sent.";
    public static final String E3_MESSAGE = "Required fields are missing or null. Please ensure all necessary fields are provided.";
    public static final String E4_MESSAGE = "The relevant category cannot be deleted or updated as it is still being used by a product or provider.";
    public static final String E5_MESSAGE = "Invalid %s provided: %s. The %s must be either %s";
    public static final String E6_MESSAGE = "An error occured while trying update the user.";
    public static final String E7_MESSAGE = "Invalid role entered.";
    public static final String E8_MESSAGE = "An error occurred while uploading data to the database.";
    public static final String E9_MESSAGE = "An error occurred while uploading the photo.";
    public static final String E10_MESSAGE = "User not found";
    public static final String E11_MESSAGE = "User not found with the id {%s}";
    public static final String E12_MESSAGE = "An error occured while trying to create the course.";
    public static final String E13_MESSAGE = "Invalid email or password.";
    public static final String E14_MESSAGE = "An error occured while logging in.";
    public static final String E15_MESSAGE = "An error occured while deleting the course.";
    public static final String E16_MESSAGE = "An error occured while searching courses.";
    public static final String E17_MESSAGE = "You are not authorized to perform this action.";
    public static final String E18_MESSAGE = "Failed to retrieve course.";
    public static final String E19_MESSAGE = "Course not found with id: {%s}";
    public static final String E20_MESSAGE = "An error occured while updating the course.";
    public static final String E21_MESSAGE = "An error occured while login in.";
    public static final String E22_MESSAGE = "An error occured while signing up.";
    public static final String E23_MESSAGE = "An error occured while refreshing the token";
    public static final String E24_MESSAGE = "An error occured while adding the user to the course.";
    public static final String E25_MESSAGE = "Cannot set user authentication.";
    public static final String E26_MESSAGE = "Error: Invalid {%s} number. {%s} must be greater than 0.";
    public static final String E27_MESSAGE = "Course not found";
    public static final String E28_MESSAGE = "One or more %s were not found with the given IDs, or duplicate %s IDs were provided.";
    public static final String E29_MESSAGE = "Error on chapter endpoint.";
}
